name: Build GlanceThing and attach to release

on:
  push:
    branches:
      - main        
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine64 wine32 -y

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build:win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glancething-windows-artifact
          path: ./dist/glancething-*-setup.exe

      - name: Upload the installer to the GitHub Release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/glancething-*-setup.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build:mac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glancething-macos-artifact
          path: ./dist/glancething-*.dmg

      - name: Upload the DMG to the GitHub Release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/glancething-*.dmg

  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Zip the build output
        run: zip -r /tmp/glancething-client-${GITHUB_REF_NAME}.zip ./*
        working-directory: ./client/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glancething-client-artifact
          path: /tmp/glancething-client-*.zip

      - name: Upload the zip to the GitHub Release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/glancething-client-*.zip
